In [1]:
import torch

**Note:** tensor Require to all there elemnts have single data type.

In [2]:
#Vectors
t1 = torch.tensor([1.,2,3,4,5])
t1

tensor([1., 2., 3., 4., 5.])

In [6]:
t1.shape

torch.Size([5])

In [4]:
#matrix
t2 = torch.tensor([[1,2,4], [3,4,5], [5,6,7]])
t2

tensor([[1, 2, 4],
        [3, 4, 5],
        [5, 6, 7]])

In [7]:
t2.shape

torch.Size([3, 3])

In [5]:
#3d Array
t3 = torch.tensor([[[1,2,3], [3,4,5], [5,6,7]], [[1,2,3], [3,4,5], [5,6,7]]])
t3


tensor([[[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]],

        [[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])

In [8]:
t3.shape

torch.Size([2, 3, 3])

**Tensor Operation with gradient**

In [18]:
# creating Tensors
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad = True)
b= torch.tensor(5., requires_grad= True)


In [22]:
#Arithmatic operation
y = w * x + b
print(y)

tensor(17., grad_fn=<AddBackward0>)


In [23]:
#compute Derivative
y.backward()


In [24]:
# lets go with one more example
z = torch.tensor(3., requires_grad = True)

In [25]:
p = z**2 + 2*z + 1
p.backward()

In [27]:
print(z.grad)

tensor(8.)


# Interoperations:

In [32]:
#Converting numpy array to pytorch tensor
import numpy as np
x = np.array([[1,2], [3,4.]])
print(x)

y = torch.from_numpy(x)
print(y)

print(x.dtype, y.dtype)
z = y.numpy()
print(z)


[[1. 2.]
 [3. 4.]]
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
float64 torch.float64
[[1. 2.]
 [3. 4.]]
